import { useState, useMemo, useEffect } from "react"
import { BASE_URL } from "@/config/constant"
import { createQuestion, deleteQuestion } from "@/lib/api"
import useFetch from "@/customHook/useFetch"
import useDebounce from "@/customHook/useDebounce"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import { formatDate } from "@/lib/utils"
import { TablePagination } from "@/components/TablePagination"
import { LoadingState } from "@/components/LoadingState"
import { ErrorState } from "@/components/ErrorState"

const PAGE_SIZE = 20

type TagItem = string | { _id: string; name: string }

type PlaylistItem = {
  _id: string | number
  title: string
  answerCount: number
  display: boolean
  tags: TagItem[]
  hidden: boolean
  creationDate?: string | number
}

function formatTags(tags: TagItem[] | undefined): string {
  if (!Array.isArray(tags)) return "—"
  return tags
    .map((t) => (typeof t === "string" ? t : t?.name ?? ""))
    .filter(Boolean)
    .join(", ") || "—"
}

type PlaylistApiResponse = {
  totalQuestions: number
  questions: PlaylistItem[]
}

const SEARCH_DEBOUNCE_MS = 300

const SORT_OPTIONS = [
  { value: "recent", label: "RECENT" },
  { value: "top", label: "POPULAR" },
  { value: "creator", label: "CREATOR" },
  { value: "answer_count_desc", label: "CLIP COUNT" },
] as const

type SortValue = (typeof SORT_OPTIONS)[number]["value"]

type MemberOption = { _id: string; name: string; title?: string }

const DEFAULT_COLORS = [
  { name: "Red", colorCode: "FF0000" },
  { name: "Blue", colorCode: "0000FF" },
  { name: "Green", colorCode: "008000" },
  { name: "Purple", colorCode: "800080" },
  { name: "Orange", colorCode: "FFA500" },
  { name: "Teal", colorCode: "008080" },
]

const defaultCreateForm = () => ({
  title: "",
  allowSameNamePlaylist: false,
  description: "",
  selectedColorName: "",
  colorCode: "",
  hidden: false,
  enableSuggestions: false,
  errorMessage: "",
})

export function Playlists() {
  const [currentPage, setCurrentPage] = useState(1)
  const [searchQuery, setSearchQuery] = useState("")
  const [userNameState, setUserNameState] = useState("")
  const [memberListOpen, setMemberListOpen] = useState(false)
  const [members] = useState<MemberOption[]>([]) // TODO: fetch from API (e.g. props.members.list)
  const [dateFrom, setDateFrom] = useState("")
  const [dateTo, setDateTo] = useState("")
  const [sort, setSort] = useState<SortValue>("recent")
  const [userFilter, setUserFilter] = useState<"all" | "verified">("all")
  const [showOnlyHidden, setShowOnlyHidden] = useState(false)
  const [hideAutogenerated, setHideAutogenerated] = useState(true)
  const [createPlaylistOpen, setCreatePlaylistOpen] = useState(false)
  const [createForm, setCreateForm] = useState(defaultCreateForm)
  const [createSubmitting, setCreateSubmitting] = useState(false)
  const [listRefreshKey, setListRefreshKey] = useState(0)
  const [confirmModal, setConfirmModal] = useState(false)
  const [deleteId, setDeleteId] = useState<string | number | null>(null)
  const [deleteSubmitting, setDeleteSubmitting] = useState(false)
  const debouncedSearch = useDebounce(searchQuery.trim(), SEARCH_DEBOUNCE_MS)

  const openCreateModal = () => {
    setCreateForm(defaultCreateForm())
    setCreatePlaylistOpen(true)
  }
  const closeCreateModal = () => {
    setCreatePlaylistOpen(false)
  }

  const openDeleteConfirm = (id: string | number) => {
    setDeleteId(id)
    setConfirmModal(true)
  }
  const closeDeleteConfirm = () => {
    setConfirmModal(false)
    setDeleteId(null)
  }
  const handleDeleteClicked = async () => {
    if (deleteId == null) return
    setDeleteSubmitting(true)
    try {
      await deleteQuestion(deleteId)
      closeDeleteConfirm()
      setListRefreshKey((k) => k + 1)
    } catch (err) {
      // Could set an error toast or inline message
      closeDeleteConfirm()
    } finally {
      setDeleteSubmitting(false)
    }
  }

  useEffect(() => {
    setCurrentPage(1)
  }, [
    debouncedSearch,
    userNameState,
    dateFrom,
    dateTo,
    sort,
    userFilter,
    showOnlyHidden,
    hideAutogenerated,
  ])

  const clearAllFilters = (e: React.MouseEvent) => {
    e.preventDefault()
    setSearchQuery("")
    setUserNameState("")
    setDateFrom("")
    setDateTo("")
    setSort("recent")
    setUserFilter("all")
    setShowOnlyHidden(false)
    setHideAutogenerated(true)
    setCurrentPage(1)
  }

  const playlistUrl = useMemo(() => {
    const params = new URLSearchParams()
    params.set("from", String((currentPage - 1) * PAGE_SIZE))
    params.set("limit", String(PAGE_SIZE))
    params.set("sort", sort)
    params.set("_refresh", String(listRefreshKey))
    if (debouncedSearch) params.set("qs", debouncedSearch)
    if (dateFrom) {
      const fromMs = new Date(dateFrom + "T00:00:00").getTime()
      params.set("fromDate", String(fromMs))
    }
    if (dateTo) {
      const toMs = new Date(dateTo + "T23:59:59.999").getTime()
      params.set("toDate", String(toMs))
    }
    if (userFilter === "verified") params.set("verifiedUser", "true")
    if (showOnlyHidden) params.set("hidden", "true")
    if (hideAutogenerated) params.set("hideAutogenratedPlaylist", "true")
    if (userNameState.trim()) {
      params.set("hideAutogenratedPlaylist", "true")
      params.set("username", userNameState.trim())
    }

    return `${BASE_URL}/dashboard-questions?${params.toString()}`
  }, [
    currentPage,
    debouncedSearch,
    listRefreshKey,
    userNameState,
    dateFrom,
    dateTo,
    sort,
    userFilter,
    showOnlyHidden,
    hideAutogenerated,
  ])

  const { data, loading, error } = useFetch(playlistUrl, {
    credentials: "include",
  })

  const { questions, totalPages, startIndex, endIndex, totalQuestions } = useMemo(() => {
    const response = data as PlaylistApiResponse | null
    const total = response?.totalQuestions ?? 0
    const list = response?.questions ?? []
    const totalPages = Math.max(1, Math.ceil(total / PAGE_SIZE))
    const start = (currentPage - 1) * PAGE_SIZE
    const startIndex = total === 0 ? 0 : start + 1
    const endIndex = Math.min(start + list.length, total)
    return {
      totalQuestions: total,
      questions: list,
      totalPages,
      startIndex,
      endIndex,
    }
  }, [data, currentPage])

  return (
      <div className="flex flex-col pb-6">
    {/* Filters Section */}
    <div className="bg-gray-50 border border-gray-200 rounded-lg p-4 space-y-4">
      <div className="flex items-center justify-between">
        <h3 className="text-lg font-medium text-gray-900">Filters</h3>
        <div className="flex items-center gap-3">
          <a
            href="#"
            onClick={clearAllFilters}
            className="text-sm text-primary hover:underline"
          >
            Clear All Filters
          </a>
          <Button onClick={openCreateModal}>
            Create Playlist
          </Button>
        </div>
      </div>

      {/* Row 1: Search text, User name, Date FROM, Date TO */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
        <div>
          <Input
            type="search"
            placeholder="Enter search text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full"
            aria-label="Search text"
          />
        </div>
        <div className="relative">
          <Input
            type="text"
            placeholder="Enter user name"
            value={userNameState}
            onChange={(e) => {
              setUserNameState(e.target.value)
              setMemberListOpen(true)
            }}
            onFocus={() => setMemberListOpen(true)}
            onBlur={() => setTimeout(() => setMemberListOpen(false), 200)}
            className="w-full"
            aria-label="User name"
          />
          {members.length > 0 && memberListOpen && (
            <div className="absolute top-full left-0 right-0 z-10 mt-1 max-h-48 overflow-auto rounded-md border border-gray-200 bg-white py-1 shadow-lg">
              {members.map((option) => (
                <button
                  key={option._id}
                  type="button"
                  className="w-full px-3 py-2 text-left text-sm hover:bg-gray-100"
                  onMouseDown={() => {
                    setUserNameState(option.name)
                    setMemberListOpen(false)
                    setListRefreshKey((k) => k + 1)
                  }}
                >
                  {option.name}
                </button>
              ))}
            </div>
          )}
        </div>
        <div>
          <Input
            type="date"
            placeholder="FROM"
            value={dateFrom}
            onChange={(e) => setDateFrom(e.target.value)}
            className="w-full"
            aria-label="Date from"
          />
        </div>
        <div>
          <Input
            type="date"
            placeholder="TO"
            value={dateTo}
            onChange={(e) => setDateTo(e.target.value)}
            className="w-full"
            aria-label="Date to"
          />
        </div>
      </div>

      {/* Row 2: Sort, Verified user, Show only Hidden, Hide Autogenerated */}
      <div className="flex flex-wrap items-center gap-4">
        <div className="flex items-center gap-2">
          <span className="text-sm text-gray-700 whitespace-nowrap">Sort By:</span>
          <Select
            value={sort}
            onValueChange={(v) => setSort(v as SortValue)}
          >
            <SelectTrigger className="w-[160px]">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {SORT_OPTIONS.map((opt) => (
                <SelectItem key={opt.value} value={opt.value}>
                  {opt.label}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
        <label className="flex items-center gap-2 cursor-pointer">
          <input
            type="checkbox"
            checked={userFilter === "verified"}
            onChange={(e) => setUserFilter(e.target.checked ? "verified" : "all")}
            className="h-4 w-4 rounded border-input"
          />
          <span className="text-sm text-gray-700">Verified user</span>
        </label>
        <label className="flex items-center gap-2 cursor-pointer">
          <input
            type="checkbox"
            checked={showOnlyHidden}
            onChange={(e) => setShowOnlyHidden(e.target.checked)}
            className="h-4 w-4 rounded border-input"
          />
          <span className="text-sm text-gray-700">Show only Hidden</span>
        </label>
        <label className="flex items-center gap-2 cursor-pointer">
          <input
            type="checkbox"
            checked={hideAutogenerated}
            onChange={(e) => setHideAutogenerated(e.target.checked)}
            className="h-4 w-4 rounded border-input"
          />
          <span className="text-sm text-gray-700">Hide Autogenerated Harklist</span>
        </label>
      </div>
    </div>

    {/* Create Playlist popup */}
    {createPlaylistOpen && (
      <div
        className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4 overflow-y-auto"
        role="dialog"
        aria-modal="true"
        aria-labelledby="create-playlist-title"
        onClick={closeCreateModal}
      >
        <div
          className="w-full max-w-lg rounded-lg bg-white p-6 shadow-xl my-8"
          onClick={(e) => e.stopPropagation()}
        >
          <h2 id="create-playlist-title" className="text-lg font-semibold text-gray-900">
            Create Playlist
          </h2>

          {createForm.errorMessage && (
            <div className="mt-3 rounded-md border border-primary/30 bg-primary/10 px-3 py-2 text-sm text-primary">
              {createForm.errorMessage}
            </div>
          )}

          <form
            className="mt-4 space-y-4"
            onSubmit={async (e) => {
              e.preventDefault()
              if (!createForm.title?.trim()) {
                setCreateForm((f) => ({ ...f, errorMessage: "Title is required" }))
                return
              }
              if (!createForm.selectedColorName || !createForm.colorCode) {
                setCreateForm((f) => ({ ...f, errorMessage: "Color is required" }))
                return
              }
              setCreateForm((f) => ({ ...f, errorMessage: "" }))
              setCreateSubmitting(true)
              const questionObj = {
                title: createForm.title.trim(),
                description: createForm.description || undefined,
                color: createForm.colorCode,
                hidden: createForm.hidden,
                allowSameNamePlaylist: createForm.allowSameNamePlaylist,
                allowSuggestion: createForm.enableSuggestions,
              }
              try {
                await createQuestion(questionObj)
                setCreateForm(defaultCreateForm())
                closeCreateModal()
                setListRefreshKey((k) => k + 1)
              } catch (err) {
                const message =
                  err instanceof Error ? err.message : "ContentURI is not Valid"
                setCreateForm((f) => ({
                  ...f,
                  errorMessage: message || "ContentURI is not Valid",
                }))
              } finally {
                setCreateSubmitting(false)
              }
            }}
          >
            <div className="grid gap-2">
              <Label htmlFor="create-title">
                Title <span className="text-destructive">*</span>
              </Label>
              <div className="relative">
                <textarea
                  id="create-title"
                  maxLength={75}
                  placeholder="Enter Harklist title"
                  value={createForm.title}
                  onChange={(e) => setCreateForm((f) => ({ ...f, title: e.target.value }))}
                  className="flex min-h-[80px] w-full rounded-md border border-input bg-transparent px-3 py-2 text-sm shadow-sm placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
                />
                <span className="absolute bottom-2 right-2 text-xs text-muted-foreground">
                  {createForm.title.length}/75
                </span>
              </div>
            </div>

            <div className="flex items-center gap-2">
              <input
                type="checkbox"
                id="create-allow-same"
                checked={createForm.allowSameNamePlaylist}
                onChange={(e) =>
                  setCreateForm((f) => ({ ...f, allowSameNamePlaylist: e.target.checked }))
                }
                className="h-4 w-4 rounded border-input"
              />
              <Label htmlFor="create-allow-same" className="font-normal">
                Allow Same Name HarkList
              </Label>
            </div>

            <div className="grid gap-2">
              <Label htmlFor="create-description">Description</Label>
              <div className="relative">
                <textarea
                  id="create-description"
                  maxLength={250}
                  placeholder="Enter Description"
                  value={createForm.description}
                  onChange={(e) => setCreateForm((f) => ({ ...f, description: e.target.value }))}
                  className="flex min-h-[100px] w-full rounded-md border border-input bg-transparent px-3 py-2 text-sm shadow-sm placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
                />
                <span className="absolute bottom-2 right-2 text-xs text-muted-foreground">
                  {createForm.description.length}/250
                </span>
              </div>
            </div>

            <div className="grid gap-2">
              <Label>
                Color <span className="text-destructive">*</span>
              </Label>
              <Select
                value={createForm.selectedColorName || undefined}
                onValueChange={(value) => {
                  const c = DEFAULT_COLORS.find((x) => x.name === value)
                  setCreateForm((f) => ({
                    ...f,
                    selectedColorName: value,
                    colorCode: c?.colorCode ?? "",
                  }))
                }}
              >
                <SelectTrigger className="w-full">
                  <SelectValue placeholder="Choose Color" />
                </SelectTrigger>
                <SelectContent>
                  {DEFAULT_COLORS.map((c) => (
                    <SelectItem key={c.name} value={c.name}>
                      <span className="flex items-center gap-2">
                        <span
                          className="inline-block h-4 w-4 rounded border border-gray-300"
                          style={{ background: `#${c.colorCode}` }}
                        />
                        {c.name}
                      </span>
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="flex items-center gap-2">
              <input
                type="checkbox"
                id="create-display"
                checked={!createForm.hidden}
                onChange={(e) =>
                  setCreateForm((f) => ({ ...f, hidden: !e.target.checked }))
                }
                className="h-4 w-4 rounded border-input"
              />
              <Label htmlFor="create-display" className="font-normal">
                Display. Deselect this to keep your Harklist private until you've added your clips.
              </Label>
            </div>

            <div className="flex items-center gap-2">
              <input
                type="checkbox"
                id="create-allow-suggestion"
                checked={createForm.enableSuggestions}
                onChange={(e) =>
                  setCreateForm((f) => ({ ...f, enableSuggestions: e.target.checked }))
                }
                className="h-4 w-4 rounded border-input"
              />
              <Label htmlFor="create-allow-suggestion" className="font-normal">
                Allow Suggestion
              </Label>
            </div>

            <div className="mt-6 flex justify-end gap-2">
              <Button
                type="button"
                variant="outline"
                onClick={closeCreateModal}
                disabled={createSubmitting}
              >
                Cancel
              </Button>
              <Button type="submit" disabled={createSubmitting}>
                {createSubmitting ? "Creating…" : "Create"}
              </Button>
            </div>
          </form>
        </div>
      </div>
    )}

    {/* Delete confirmation modal */}
    {confirmModal && (
      <div
        className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"
        role="dialog"
        aria-modal="true"
        aria-labelledby="delete-confirm-title"
        onClick={closeDeleteConfirm}
      >
        <div
          className="w-full max-w-md rounded-lg bg-white p-6 shadow-xl"
          onClick={(e) => e.stopPropagation()}
        >
          <h2 id="delete-confirm-title" className="text-lg font-semibold text-gray-900">
            Confirmation
          </h2>
          <p className="mt-3 text-sm text-gray-600">
            Do you really want to delete this harklist?
          </p>
          <div className="mt-6 flex justify-end gap-2">
            <Button
              type="button"
              variant="outline"
              onClick={closeDeleteConfirm}
              disabled={deleteSubmitting}
            >
              Cancel
            </Button>
            <Button
              type="button"
              variant="destructive"
              onClick={handleDeleteClicked}
              disabled={deleteSubmitting}
            >
              {deleteSubmitting ? "Deleting…" : "Delete"}
            </Button>
          </div>
        </div>
      </div>
    )}

    {error && <ErrorState message={String(error)} />}

    <div className="relative mt-4">
      {loading && (
        <LoadingState overlay message="Loading playlists…" />
      )}
      <div className="bg-white border border-gray-200 rounded-lg overflow-hidden">
        <table className="w-full table-auto">
          <thead className="bg-gray-100 border-b border-gray-200">
            <tr>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">
                ID
              </th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">
                title
              </th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">
                Clip Count
              </th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">
                Display
              </th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">
                Tags
              </th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">
                 Date
              </th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">
                Actions
              </th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-200">
            {questions.length === 0 ? (
              <tr>
                <td colSpan={3} className="px-6 py-8 text-center text-gray-500">
                  No Playlists found
                </td>
              </tr>
            ) : (
              questions.map((Q) => (
                <tr key={Q._id} className="hover:bg-gray-50 transition-colors">
                  <td className="px-6 py-4 text-sm text-gray-600">{Q._id}</td>
                  <td className="px-6 py-4 text-sm font-medium text-gray-900">{Q.title}</td>
                  <td className="px-6 py-4 text-sm text-gray-600">{Q.answerCount}</td>
                  <td className="px-6 py-4 text-sm text-gray-600">{Q.hidden ? <span className="linkStyle">hidden</span> : ''}</td>
                  <td className="px-6 py-4 text-sm text-gray-600">{formatTags(Q.tags)}</td>
                  <td className="px-6 py-4 text-sm text-gray-600">{formatDate(Q.creationDate)}</td>
                  <td className="px-6 py-4 text-sm text-gray-600">
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => openDeleteConfirm(Q._id)}
                    >
                      Delete
                    </Button>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>
    </div>

    <TablePagination
      currentPage={currentPage}
      totalPages={totalPages}
      onPageChange={setCurrentPage}
      startIndex={startIndex}
      endIndex={endIndex}
      total={totalQuestions}
      itemLabel="playlists"
    />
    </div>
  )
}